name: communify
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Logs
  firebase_crashlytics: ^3.3.3
  log_service:
    path: log_service

  #Tools
  provider: ^6.0.5
  path_provider: ^2.0.15
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  cached_network_image: ^3.2.3

  #Router
  go_router: ^8.0.5

  #Network
  dio: ^5.2.1+1
  retrofit: ^4.0.1

  #Storage
  shared_preferences: ^2.1.2

  #BLoC
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.3
  build_runner: ^2.4.4
  flutter_lints: ^2.0.1
  json_serializable: ^6.7.0
  retrofit_generator: ^7.0.1

flutter:
  uses-material-design: true
