name: communify
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Logs
  firebase_crashlytics: ^3.3.3
  log_service:
    path: log_service

  #Tools
  provider: ^6.0.5
  path_provider: ^2.0.15
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  cached_network_image: ^3.2.3

  #Router
  go_router: ^8.0.5

  #Network
  dio: ^5.2.1+1
  retrofit: ^4.0.1

  #Storage
  shared_preferences: ^2.1.2

  #BLoC
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2

  #Localization
  flutter_localizations:
    sdk: flutter
  intl: any

  #UI
  flutter_svg: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.3
  build_runner: ^2.4.4
  flutter_lints: ^2.0.1
  json_serializable: ^6.7.0
  retrofit_generator: ^7.0.1
  intl_utils: ^2.8.2
  flutter_gen_runner: ^5.3.1

flutter_gen:
  integrations:
    flutter_svg: true
  assets:
    enabled: true
    outputs:
      class_name: AppAssets

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
  fonts:
    - family: Karla
      fonts:
        - asset: assets/fonts/Karla-Regular.ttf
          weight: 400
        - asset: assets/fonts/Karla-Medium.ttf
          weight: 500
        - asset: assets/fonts/Karla-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 800
flutter_intl:
  enabled: true
